import os
import pytest
from src.structured_query import get_sqlite_schema, execute_sql_query, answer_structured_query
from src.config import DATABASE_PATH

def test_get_sqlite_schema():
    assert os.path.exists(DATABASE_PATH), "Database file must exist to run tests."
    schema = get_sqlite_schema(DATABASE_PATH)
    assert "CREATE TABLE transactions" in schema
    assert "date" in schema
    assert "description" in schema
    assert "amount" in schema

def test_execute_sql_query():
    sql = "SELECT COUNT(*) FROM transactions;"
    cols, rows = execute_sql_query(DATABASE_PATH, sql)
    assert cols == ["COUNT(*)"]
    assert len(rows) == 1
    assert rows[0][0] == 56  # 14 rows * 4 months

def test_answer_structured_query_salary():
    q = "What was my TechCorp salary in January 2026?"
    res = answer_structured_query(q)
    assert res["success"] is True
    assert "SELECT" in res["sql"].upper()
    assert len(res["results"]) == 1
    # TechCorp Salary is 5000.0
    assert float(res["results"][0][0]) == 5000.0

def test_answer_structured_query_total_spend():
    q = "What is the total spend in March 2026?"
    res = answer_structured_query(q)
    assert res["success"] is True
    assert len(res["results"]) == 1
    # January ending balance: 3500 starting. Rent: -1500, Groceries: -112.4, etc.
    # Total withdrawals sum up to -2243.83 (as generated by script overview table in March)
    val = abs(float(res["results"][0][0]))
    assert pytest.approx(val, 0.01) == 2243.83
